services:
  consume-user-interface:
    container_name: consume-user-interface
    image: ghcr.io/data-space-core/consume-user-interface-2/stage:latest
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    platform: linux/amd64
    volumes:
      - .env:/app/.env
    ports:
      - "8001:8000"
